python main.py \
    --data_path '../data/PEMS03/PEMS03.npz' \
    --adj_filename '../data/PEMS03/PEMS03.csv' \
    --dataset PEMS03FLOW \
    --desc PEMS03_pre\
    --sample_len 12 \
    --predict_len 12 \
    --train_ratio 0.6 \
    --val_ratio 0.2 \
    --epoch 500 \
    --val_epoch 1 \
    --test_epoch 5 \
    --batch_size 64\
    --lr 0.001 \
    --causal 0 \
    --patience 50 \
    --ln_grad \
    --lora \
    --t_dim 64 \
    --node_emb_dim 64 \
    --node_embedding \
    --llm_layers 3 \
    --time_token \
    --dropout 0.05 \
    --trunc_k 64 \
    --weight_decay 0 \
    --task prediction \
    --sandglassAttn \
    --sag_dim 128 \
    --sag_tokens 128 \
    --input_dim 1\
    --output_dim 1\
    --device cuda\
    --normalized_k 0.1\
    --causal_ratio 0.7\
    --alpha 1e-8\
    --quantile_k 0.5\
    --log_root ../logs\
    --model gpt2\
    --num_nodes 358\
    --max_increase_ratio 0.0 \
    --test_increase_ratio 0.0 \
    --test_decrease_ratio 0.0 